version: '3.8'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=./data.db
      - NODE_ENV=development

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=production
