version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337" # Backend port
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app/api
      - ./frontend:/app/client
