name: Github Actions Workflow

on: 
  push:
    branches: [master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-lastest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    env:
      HOST: '0.0.0.0'
      PORT: '1337'
      APP_KEYS: 'mock'
      API_TOKEN_SALT: 'mock'
      #TRANSFER_TOKEN_SALT: 'mock'
      #DATABASE_CLIENT: 'sqlite'
      #DATABASE_FILENAME: '.tmp/data.db'
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
      STRAPI_ADMIN_CLIENT_PREVIEW_SECRET: ${{ secrets.STRAPI_ADMIN_CLIENT_PREVIEW_SECRET }}


    steps:
    - name: Check code
      uses: actions/checkout@v4
    - name: Setup node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
      working-directory: ./api

    - name: Build project  
      run: yarn build
      working-directory: ./api

    - name: Test  
      run: 
        yarn test
        echo "my STRAPI_ADMIN_CLIENT_PREVIEW_SECRET is ${{ secrets.STRAPI_ADMIN_CLIENT_PREVIEW_SECRET }}"
      working-directory: ./api
