name: Github Actions Workflow

on: 
  push:
    branches: [master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check code
      uses: actions/checkout@v4

    - name: Setup node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies in api
      run: yarn
      working-directory: ./api

    - name: Build project  
      run: yarn build
      working-directory: ./api

    - name: Install dependencies in client
      run: yarn
      working-directory: ./client

    - name: Test unit test client
      run:
        yarn test
        #     echo "my STRAPI_ADMIN_CLIENT_PREVIEW_SECRET is ${{ secrets.STRAPI_ADMIN_CLIENT_PREVIEW_SECRET }}"
      working-directory: ./client
 
    

